---
- hosts: all
  vars:
    local_home: "{{ lookup('env','HOME') }}"
    local_user: "{{ lookup('env','USER') }}"
  tasks:
    - name: copy ssh pub key
      authorized_key: user="{{ local_user }}" key="{{ lookup('file',"/Users/jolexa/.ssh/id_rsa.pub") }}"

    - name: copy and update dotfiles
      copy: src={{ item }} dest={{ ansible_env.HOME }}/.{{ item | basename }}
      with_fileglob:
        - files/*

#    - name: copy and update vim plugins
#      copy: src=files/vim/ dest={{ ansible_env.HOME }}/.vim/ force=yes
    - name: rsync vim plugins
      synchronize: src=files/vim/ dest={{ ansible_env.HOME }}/.vim delete=yes



# vim:ft=ansible:
