# This file is sourced by bash for login shells.  The following line
# runs your .bashrc and is recommended by the bash info pages.
[[ -f ~/.bashrc ]] && . ~/.bashrc

if [[ $(type -P keychain) ]]; then
        eval `keychain -q --eval id_rsa_sps sysops-jolexa`
fi
